name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x64 - Primary target
          - os: ubuntu-latest
            platform: Linux x64
            artifact: necromancer_shell-linux-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ===== Linux Dependencies =====
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libncurses5-dev \
            libncursesw5-dev \
            cppcheck

      # ===== Build =====
      - name: Build release
        working-directory: necromancers_shell
        env:
          CI: true
        run: make release

      - name: Build debug
        working-directory: necromancers_shell
        env:
          CI: true
        run: make debug

      # ===== Tests =====
      - name: Run unit tests
        working-directory: necromancers_shell
        run: make test

      # ===== Static Analysis =====
      - name: Run static analysis
        working-directory: necromancers_shell
        run: make analyze

      # ===== Memory Check =====
      # Note: Memory safety is checked via Address Sanitizer (ASan) and
      # Undefined Behavior Sanitizer (UBSan) in the debug build above.
      # Valgrind cannot run with ASan enabled, so we skip it.
      # The sanitizers provide comprehensive memory checking including:
      # - Memory leaks
      # - Use-after-free
      # - Buffer overflows
      # - Undefined behavior

      # ===== Upload Artifacts =====
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            necromancers_shell/build/necromancer_shell*
            !necromancers_shell/build/**/*.o
            !necromancers_shell/build/**/*.d
          if-no-files-found: error
          retention-days: 7

      # ===== Upload test results on failure =====
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.platform }}
          path: |
            necromancers_shell/*.log
          if-no-files-found: ignore
          retention-days: 7
