name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x64 - Primary target
          - os: ubuntu-latest
            platform: Linux x64
            artifact: necromancer_shell-linux-x64

          # macOS ARM64 - Apple Silicon (recommended)
          - os: macos-15
            platform: macOS ARM64
            artifact: necromancer_shell-macos-arm64

          # macOS Intel - Legacy support
          - os: macos-15-large
            platform: macOS x64
            artifact: necromancer_shell-macos-x64

          # Windows x64 - PDCurses with MinGW
          - os: windows-latest
            platform: Windows x64
            artifact: necromancer_shell-windows-x64
            msystem: UCRT64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ===== Linux Dependencies =====
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libncurses5-dev \
            libncursesw5-dev \
            valgrind \
            cppcheck

      # ===== macOS Dependencies =====
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ncurses cppcheck

      # ===== Windows Dependencies =====
      - name: Setup MSYS2 (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-pdcurses
            make

      # ===== Build =====
      - name: Build release
        working-directory: necromancers_shell
        env:
          CI: true
        run: make release

      - name: Build debug
        working-directory: necromancers_shell
        env:
          CI: true
        run: make debug

      # ===== Tests =====
      - name: Run unit tests
        working-directory: necromancers_shell
        run: make test

      # ===== Static Analysis (Linux only) =====
      - name: Run static analysis
        if: runner.os == 'Linux'
        working-directory: necromancers_shell
        run: make analyze

      # ===== Memory Check (Linux only) =====
      - name: Check for memory leaks (Linux)
        if: runner.os == 'Linux'
        working-directory: necromancers_shell
        run: |
          make valgrind || true
          if [ -f valgrind-out.txt ]; then
            if grep -q "definitely lost: 0 bytes" valgrind-out.txt; then
              echo "✓ No memory leaks detected"
            else
              echo "✗ Memory leaks detected!"
              cat valgrind-out.txt
              exit 1
            fi
          fi

      - name: Memory leak detection note (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "ℹ️  Valgrind not available on Windows"
          echo "Memory leak detection relies on:"
          echo "  - Debug build with extra checks"
          echo "  - Linux/macOS CI valgrind verification"
          echo "  - Manual testing with Dr. Memory (optional)"
          echo ""
          echo "For local memory leak testing on Windows, install Dr. Memory:"
          echo "  https://drmemory.org/"

      # ===== Upload Artifacts =====
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            necromancers_shell/build/necromancer_shell*
            !necromancers_shell/build/**/*.o
            !necromancers_shell/build/**/*.d
          if-no-files-found: error
          retention-days: 7

      # ===== Upload test results on failure =====
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.platform }}
          path: |
            necromancers_shell/*.log
            necromancers_shell/valgrind-out.txt
          if-no-files-found: ignore
          retention-days: 7
